---
- name: Factorio server
  hosts: all
  remote_user: ec2-user
  become: true
  become_method: sudo
  gather_facts: False

  roles:
    - role: bplower.factorio
      service_port: 50000
      server_version: 0.17.79
      factorio_server_settings:
        name: "Factorio cloud test"
        max_players: 8
        game_password: "notthatsecret"
        visibility:
          public: false
        autosave_interval: 30
        autosave_slots: 20
      factorio_map_settings_enabled: true
      factorio_map_settings:
        pollution:
          enabled: false
    - role: aws_volume_mount
      block_device_data:
        - name: sdx
          filesystem: ext4
          mount_point: /opt/factorio
